- hosts: dbservers
  remote_user: root
  vars:
    postgresql_version: 9.5
    postgresql_conf:
      listen_addresses: "'192.168.58.14'"    # disable network listening (listen on unix socket only)
      max_connections: 50       # decrease connection limit
    postgresql_pg_hba_conf:
      - host   all     postgres      192.168.58.19/32       trust
      - host   metastore     hive      192.168.58.0/24       md5
  roles:
    - postgresql
